version: '{branch}-{build}'
skip_non_tags: true
platform:
- x86
- x64
init:
- cmd: IF %APPVEYOR_REPO_TAG%==true appveyor UpdateBuild -Version %APPVEYOR_REPO_TAG_NAME%-%APPVEYOR_BUILD_NUMBER%
before_build:
- cmd: >-
    appveyor DownloadFile http://www.wheaty.net/libctiny.zip

    7z e *.zip *printf.cpp ATOL.cpp

    DEL *.zip
build_script:
- cmd: build.bat
after_build:
- cmd: 7z a minicrt-%Platform%.zip *.lib
artifacts:
- path: '*.zip'
  name: minicrt
deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: zIYDdLSpTYfwor3/yVTOVcQ8Aba6ZKA/+0veD02VWkbNdOQ8Q/YhABfSqaRF40UB
  artifact: /.*\.zip/
  on:
    APPVEYOR_REPO_TAG: true
